### ISSUE TITLE
Issues with horizontal scroll and left menu

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#721]
After scrolling horizontally the page content is displayed above the left menu.
I can reproduce this on Linux/Firefox and Linux/Chrome

![scroll_issues](https://user-images.githubusercontent.com/5910449/37660488-d571010e-2c52-11e8-91ef-50398b9961b1.png)

**Comment by tn12787** [comment]
The white background on your doc page suggests your cache is far out of date.

Can you please let me know what happens after clearing the cache?

**Comment by stefaniapedrazzi** [comment]
The cache is not outdated: I cleared many times today.
The blue background is simply not visible because the window width is too small.

**Comment by tn12787** [comment]
Ah, I see. Thanks for the explanation.

**Comment by stefaniapedrazzi** [comment]
I get the exact same issue using the offline doc in Webots.

**Comment by tn12787** [comment]
@fabienrohrer and I just found the issue. It's to do with word-breaking. Fix incoming!

**Comment by fabienrohrer** [comment]
Fixed locally #727, but not on the website due to the footer.

**Comment by fabienrohrer** [comment]
We just looked at this with Tom and it seems the simplest solution is to be coherent with the overflow of the header, that is, to be cut in case the window width is too small. This tradeoff is used in other websites (like soundcloud.com).
Better solutions could be achieved if the header and footer of the website were responsive, but we are far from this.

For now, I propose to simply fix this by changing main.css to:

```
#footer {
+ overflow-x: hidden;
- min-width: 920px;
}
```

**Comment by omichel** [comment]
Unfortunately, this doesn't fully fix the problem. I can still display the wrong layout in Chrome and Firefox:
![image](https://user-images.githubusercontent.com/1264964/41347424-e8b291d4-6f09-11e8-86f2-6c803768b26e.png)

**Comment by omichel** [comment]
I just published this patch on the web site, so that you can try it.

**Comment by omichel** [comment]
No, I removed it from the site as it screw up the footer (when the window is small and you scroll right, the footer looks really bad).

**Comment by tn12787** [comment]
I wonder whether it's not the contribution banner that's causing problems here, or maybe margin - I will continue to investigate.

**Comment by fabienrohrer** [comment]
Ok, thank you Tom
